### ISSUE TITLE
grid_stride_range and parallel_for want explicit cast betwen int and size_t

### ISSUE THREAD

**Issue by crusaderky** [harrism/hemi#19]
The following code won't compile (nvcc 7.5 + g++ 4.9):

hemi::Array<int>a(10);
int *ad = a.writeOnlyPtr();
hemi::parallel_for(0, a.size(), [=] HEMI_LAMBDA(int i) {
        ad[i] = 1;
}

The problem is that 0 is an int and a.size() is a size_t.
grid_stride_range has the same problem.

Workaround: replace 0 with (size_t)0, which however is ugly and counter-intuitive.

**Comment by harrism** [comment]
Fixing this would mean changing the type of a.size() (and the internals) to `int` from `size_t`. I am torn about this. My concern is that even if I do this, you could imagine another type (such as a std::vector) that has the same problem, and you would still end up using (size_t)0. So I'm not sure this is worth the change. Unless you have other suggestions or arguments?

**Comment by crusaderky** [comment]
Why don't you simply change grid_stride_range(T,  T)  to (size_t, size_t) ?
The compiler will then take care of auto casting. I really can't get what
the benefit is of using a template for it...

**Comment by harrism** [comment]
Fixed by 3adb866. Closing.
