### ISSUE TITLE
Hello World with hemi::Array doesn't work, but doesn't error either

### ISSUE THREAD

**Issue by JorySchossau** [harrism/hemi#30]
I tried a minimal hello world multiply input by 2 and store back into array example, and nothing happens, as if the lazy `HostToDevice` and `DeviceToHost` copying in `hemi::Array` isn't being called. Code below.

	// using GNU/6.3.0 and CUDA/9.0
	// nvcc -o test test.cpp -std=c++14 -lcuda -Ihemi -x cu && ./test

	#include <cstdio>
	#include <numeric> // iota
	#include "hemi/hemi.h"
	#include "hemi/array.h"
	#include "hemi/launch.h"
	#include "hemi/device_api.h"
	#include "hemi/execution_policy.h"

	// strangely prints ex: "setting data[3]=0", "setting data[1]=0", etc.
	HEMI_LAUNCHABLE void Kernel(int *data) {
	   printf("setting data[%d]=%d\n",hemi::globalThreadIndex(),data[hemi::globalThreadIndex()]*2);
	   data[hemi::globalThreadIndex()] *= 2;
	   __syncthreads(); // no error here means this is definitely running on the device.
	}

	int main() {
	    const int THREADS(4);

	    // delcare and init with [0, 1, 2, 3]
	    hemi::Array<int> d(THREADS, false);
	    std::iota(d.writeOnlyHostPtr(), d.writeOnlyHostPtr()+THREADS, 0);

	    // invoke device and sync
	    hemi::ExecutionPolicy ep;
	    ep.setGridSize(THREADS);
	    ep.setBlockSize(1);
	    hemi::cudaLaunch(ep, Kernel, d.writeOnlyDevicePtr());
	    hemi::deviceSynchronize();

	    cudaError_t error = cudaGetLastError();
	    if(error != cudaSuccess)
	    {
		    // print the CUDA error message and exit
		    printf("CUDA error: %s\n", cudaGetErrorString(error));
		    exit(-1);
	    }

	    // print all 4 results: expect [0, 2, 4, 6]
	    printf("results: ");
	    for (int i=0; i<THREADS; i++) {
	       printf("%d ",d.readOnlyHostPtr()[i]); // produces uninitialized data [0, 0, 0, 0] why?
	       //printf("%d ",d.writeOnlyHostPtr()[i]); // produces pre-kernel data [0, 1, 2, 3] why?
	    }
	    printf("\n");

            return(0);
	}

**Comment by frobnitzem** [comment]
Change:

    hemi::cudaLaunch(ep, Kernel, d.writeOnlyDevicePtr());

To:

    hemi::cudaLaunch(ep, Kernel, d.devicePtr());
